/*
 * Copyright 2015-2018 Micro Focus or one of its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.cafdataprocessing.corepolicy.common;

/**
 * http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
 */
public class IsoToLanguageEnumConverter {
    public static LanguagesEnum convert(String isoLanguageCode){
        isoLanguageCode = isoLanguageCode.toLowerCase();
        switch(isoLanguageCode){
            case "af":
            case "afr":
                return LanguagesEnum.Afrikaans;
            case "alb":
            case "sq":
                return LanguagesEnum.Albanian;
            case "amh":
            case "am":
                return LanguagesEnum.Amharic;
            case "ara":
            case "ar":
                return LanguagesEnum.Arabic;
            case "arm":
            case "hy":
                return LanguagesEnum.Armenian;
            case "aze":
            case "az":
                return LanguagesEnum.Azeri;
            case "baq":
            case "eu":
                return LanguagesEnum.Basque;
            case "bel":
            case "be":
                return LanguagesEnum.Belarussian;
            case "ben":
            case "bn":
                return LanguagesEnum.Bengali;
            case "ber":
                return LanguagesEnum.Berber;
            case "bre":
            case "br":
                return LanguagesEnum.Breton;
            case "bul":
            case "bg":
                return LanguagesEnum.Bulgarian;
            case "bur":
            case "my":
                return LanguagesEnum.Burmese;
            case "cat":
            case "ca":
                return LanguagesEnum.Catalan;
            case "chr":
                return LanguagesEnum.Cherokee;
            case "chi":
            case "zh":
                return LanguagesEnum.Chinese;
            case "hrv":
            case "hr":
                return LanguagesEnum.Croatian;
            case "cze":
            case "cs":
                return LanguagesEnum.Czech;
            case "dan":
            case "da":
                return LanguagesEnum.Danish;
            case "dut":
            case "nl":
                return LanguagesEnum.Dutch;
            case "eng":
            case "en":
                return LanguagesEnum.English;
            case "epo":
            case "eo":
                return LanguagesEnum.Esperanto;
            case "est":
            case "et":
                return LanguagesEnum.Estonian;
            case "fao":
            case "fo":
                return LanguagesEnum.Faroese;
            case "fin":
            case "fi":
                return LanguagesEnum.Finnish;
            case "fre":
            case "fr":
                return LanguagesEnum.French;
            case "gla":
            case "gd":
                return LanguagesEnum.Gaelic;
            case "geo":
            case "ka":
                return LanguagesEnum.Georgian;
            case "ger":
            case "de":
                return LanguagesEnum.German;
            case "gre":
            case "el":
                return LanguagesEnum.Greek;
            case "kal":
            case "kl":
                return LanguagesEnum.Greenlandic;
            case "guj":
            case "gu":
                return LanguagesEnum.Gujarati;
            case "heb":
            case "he":
                return LanguagesEnum.Hebrew;
            case "hin":
            case "hi":
                return LanguagesEnum.Hindi;
            case "hun":
            case "hu":
                return LanguagesEnum.Hungarian;
            case "ice":
            case "is":
                return LanguagesEnum.Icelandic;
            case "ind":
            case "id":
                return LanguagesEnum.Indonesian;
            case "ita":
            case "it":
                return LanguagesEnum.Italian;
            case "jpn":
            case "ja":
                return LanguagesEnum.Japanese;
            case "kan":
            case "kn":
                return LanguagesEnum.Kannada;
            case "kaz":
            case "kk":
                return LanguagesEnum.Kazakh;
            case "khm":
            case "km":
                return LanguagesEnum.Khmer;
            case "kor":
            case "ko":
                return LanguagesEnum.Korean;
            case "kur":
            case "ku":
                return LanguagesEnum.Kurdish;
            case "lao":
            case "lo":
                return LanguagesEnum.Lao;
            case "lat":
            case "la":
                return LanguagesEnum.Latin;
            case "lav":
            case "lv":
                return LanguagesEnum.Latvian;
            case "lit":
            case "lt":
                return LanguagesEnum.Lithuanian;
            case "ltz":
            case "lb":
                return LanguagesEnum.Luxembourgish;
            case "mac":
            case "mk":
                return LanguagesEnum.Macedonian;
            case "mal":
            case "ml":
                return LanguagesEnum.Malayalam;
            case "mlt":
            case "mt":
                return LanguagesEnum.Maltese;
            case "mao":
            case "mi":
                return LanguagesEnum.Maori;
            case "mon":
            case "mn":
                return LanguagesEnum.Mongolian;
            case "nep":
            case "ne":
                return LanguagesEnum.Nepali;
            case "nor":
            case "no":
                return LanguagesEnum.Norwegian;
            case "ori":
            case "or":
                return LanguagesEnum.Oriya;
            case "per":
            case "fa":
                return LanguagesEnum.Persian;
            case "pol":
            case "pl":
                return LanguagesEnum.Polish;
            case "por":
            case "pt":
                return LanguagesEnum.Portuguese;
            case "pus":
            case "ps":
                return LanguagesEnum.Pushto;
            case "rum":
            case "ro":
                return LanguagesEnum.Romanian;
            case "rus":
            case "ru":
                return LanguagesEnum.Russian;
            case "srp":
            case "sr":
                return LanguagesEnum.Serbian;
            case "snd":
            case "sd":
                return LanguagesEnum.Sindhi;
            case "sin":
            case "si":
                return LanguagesEnum.Singhalese;
            case "slo":
            case "sk":
                return LanguagesEnum.Slovak;
            case "slv":
            case "sl":
                return LanguagesEnum.Slovenian;
            case "som":
            case "so":
                return LanguagesEnum.Somali;
            case "spa":
            case "es":
                return LanguagesEnum.Spanish;
            case "swa":
            case "sw":
                return LanguagesEnum.Swahili;
            case "swe":
            case "sv":
                return LanguagesEnum.Swedish;
            case "syr":
            case "syc":
                return LanguagesEnum.Syriac;
            case "tgl":
            case "tl":
                return LanguagesEnum.Tagalog;
            case "tgk":
            case "tg":
                return LanguagesEnum.Tajik;
            case "tam":
            case "ta":
                return LanguagesEnum.Tamil;
            case "tel":
            case "te":
                return LanguagesEnum.Telugu;
            case "tha":
            case "th":
                return LanguagesEnum.Thai;
            case "tib":
            case "bo":
                return LanguagesEnum.Tibetan;
            case "tur":
            case "tr":
                return LanguagesEnum.Turkish;
            case "ukr":
            case "uk":
                return LanguagesEnum.Ukrainian;
            case "urd":
            case "ur":
                return LanguagesEnum.Urdu;
            case "uig":
            case "ug":
                return LanguagesEnum.Uyghur;
            case "uzb":
            case "uz":
                return LanguagesEnum.Uzbek;
            case "vie":
            case "vi":
                return LanguagesEnum.Vietnamese;
            case "wel":
            case "cy":
                return LanguagesEnum.Welsh;
        }
        return LanguagesEnum.English;
    }
}
